services:
  odoo17:
    image: jisreal/odoo-17-nightly-ubu-amd64:latest
    container_name: docker_odoo17
    restart: unless-stopped             # run as a service    
    ports:
      - "127.0.0.1:8069:8069"
      - "127.0.0.1:22:222"
      - "80:80"
